import Lake
open Lake DSL

package IDTProofs where

lean_exe idt_v8_protocol_status where
  root := `Experiments.V8ProtocolStatus

lean_lib Proofs where
  roots := #[
    `Proofs.IDTCore,
    `Proofs.MetaLang.V8VerificationLanguage,
    `Proofs.MetaLang.V8ContextFirstPrimitiveBase,
    `Proofs.MetaLang.V8TheoremCardLedger,
    `Proofs.MetaLang.V8CurrentStatusSnapshot,
    `Proofs.MetaLang.V8ExternalCheckerBoundary,
    `Proofs.MetaLang.V8StatusTransitionPolicy,
    `Proofs.MetaLang.V8DependencyGraphPolicy,
    `Proofs.MetaLang.V8ProofArtifactContract,
    `Proofs.MetaLang.V8LeanFirstTrustKernel,
    `Proofs.MetaLang.V8CoreClaimDisciplineRules,
    `Proofs.MetaLang.V8ControlledVocabularyInventory,
    `Proofs.MetaLang.V8ManifestCollectionContract,
    `Proofs.MetaLang.V8RuleManifestGrounding,
    `Proofs.MetaLang.V8AssertionPredicateSemantics,
    `Proofs.MetaLang.V8CoreRuleSemanticClosure,
    `Proofs.MetaLang.V8DeclarativeReportContract,
    `Proofs.MetaLang.V8ClaimStrengthInvariant,
    `Proofs.MetaLang.V8VerifierDecommissionPolicy,
    `Proofs.MetaLang.V8DeclarativeDocumentSchema,
    `Proofs.MetaLang.V8CoreClaimDisciplineDocument,
    `Proofs.MetaLang.V8SymbolResidualDocument,
    `Proofs.MetaLang.V8EquationResidualDocument,
    `Proofs.MetaLang.V8DerivationResidualDocument,
    `Proofs.MetaLang.V8QmExperimentResidualDocument,
    `Proofs.MetaLang.V8QmUniversalPatternResidualDocument,
    `Proofs.MetaLang.V8QmCoreObligationDocument,
    `Proofs.MetaLang.V8TheoremCardResidualDocument,
    `Proofs.MetaLang.V8FiniteGateResidualDocument,
    `Proofs.MetaLang.V8MigrationRoadmap,
    `Proofs.MetaLang.V8ManifestInputBoundary,
    `Proofs.MetaLang.V8ResidualMigrationLedger,
    `Proofs.MetaLang.V8MigrationStopBoundary,
    `Proofs.MetaLang.V8FormalProofScopeBoundary,
    `Proofs.MetaLang.V8ResidualRouteClassification,
    `Proofs.MetaLang.V8TaskBlockerLedger,
    `Proofs.MetaLang.V8CurrentMigrationState,
    `Proofs.MetaLang.V8CurrentTheoremAndObligationLedger,
    `Proofs.MetaLang.V8TheoremDependencyBoundaryLedger,
    `Proofs.MetaLang.V8CurrentFrontierBlockers,
    `Proofs.MetaLang.V8ResidualGateExperimentProfile,
    `Proofs.MetaLang.V8ResidualEncodingRequirements,
    `Proofs.MetaLang.V8MigrationCompletionCriterion,
    `Proofs.MetaLang.V8QmExperimentResidualLedger,
    `Proofs.MetaLang.V8LeanExperimentProtocolBoundary,
    `Proofs.MetaLang.V8ExperimentProgramReadiness,
    `Proofs.MetaLang.V8CurrentStopReadiness,
    `Proofs.MetaLang.V8AcceptedDocumentInventory,
    `Proofs.MetaLang.V8ExecutableBoundaryCheck,
    `Proofs.MetaLang.V8StoppedResearchFrontier,
    `Proofs.QMClosure.CGSCPackageClosure,
    `Proofs.QMClosure.CGSCPrimitiveBridge,
    `Proofs.QMClosure.CGSCSemanticContentWall,
    `Proofs.QMClosure.CGSCTypedSemanticExtensions,
    `Proofs.QMClosure.CGSCTypedDecorativeWall,
    `Proofs.QMClosure.CGSCGroundedSemanticExtensions,
    `Proofs.QMClosure.FullQMAssemblyFromGroundedSources,
    `Proofs.QMClosure.CGSCGroundedToyWall,
    `Proofs.QMClosure.UniversalPrimitiveSourceKernel,
    `Proofs.QMClosure.UniversalPrimitiveToyWall,
    `Proofs.QMClosure.PrimitiveGeneratedSourceKernel,
    `Proofs.QMClosure.PrimitiveGeneratedAdmissibilityWall,
    `Proofs.QMClosure.BoundPrimitiveGeneratedBase,
    `Proofs.QMClosure.B1PrimitiveBase,
    `Proofs.QMClosure.QMSemanticKernelRoute,
    `Proofs.QMClosure.ProjectionScaffoldsDraft,
    `Proofs.QMClosure.ReadoutScaffoldsDraft,
    `Proofs.QMClosure.InheritanceScaffoldsDraft,
    `Proofs.QMClosure.CompositeScaffoldsDraft,
    `Proofs.QMClosure.MonoidalAssociativityDraft,
    `Proofs.QMClosure.ProjectiveLimitScaffoldDraft,
    `Proofs.QMClosure.BoundaryScaffoldsDraft,
    `Proofs.QMClosure.QMSemanticContentScaffoldBundle,
    `Proofs.QMClosure.CGSCStructuralTargetKernel,
    `Proofs.QMClosure.B1CGSCClauseDerivation,
    `Proofs.QMClosure.BornWallSeparation,
    `Proofs.QMClosure.SchrodingerGeneratorLogic,
    `Proofs.QMClosure.S2BornProofSearch,
    `Proofs.QMClosure.PrimitiveBoundaryQMChain,
    `Proofs.QMClosure.ConstructiveWitnessPrimitiveBase,
    `Proofs.QMClosure.BornHilbertUniversalClosure,
    `Proofs.QMClosure.FullQMSectorClosure
  ]
