-- Generated by scripts/sync_formal_proof_ledger.py. Do not edit by hand.

namespace IDT

def currentFormalClaimRefs : List String :=
  [
    "finite_gates.idt_core_bounded_arity_frontier_demo.bounded_correlation_arity_bound.status",
    "finite_gates.idt_core_bounded_arity_frontier_demo.context_product_arity_bound.status",
    "finite_gates.idt_core_bounded_arity_frontier_demo.recoverable_filter_arity_bound.status",
    "finite_gates.idt_core_bounded_arity_frontier_demo.state_effect_witness_arity_bound.status",
    "finite_gates.idt_core_finite_signature_frontier_demo.finite_claim_role_vocabulary.status",
    "finite_gates.idt_core_finite_signature_frontier_demo.finite_gate_type_registry.status",
    "finite_gates.idt_core_finite_signature_frontier_demo.finite_primitive_sort_vocabulary.status",
    "finite_gates.idt_core_finite_signature_frontier_demo.finite_route_family_registry.status",
    "finite_gates.idt_core_gate_type_registry_audit_demo.idt_core_gate_type_registry_audit_demo.expected_component_status",
    "finite_gates.idt_core_no_new_primitive_effects_frontier_demo.finite_effect_registry.status",
    "finite_gates.idt_core_no_new_primitive_effects_frontier_demo.joint_only_invariant_rejection.status",
    "finite_gates.idt_core_no_new_primitive_effects_frontier_demo.route_closure_effect_audit.status",
    "finite_gates.idt_core_route_generator_basis_frontier_demo.bounded_correlation_generators.status",
    "finite_gates.idt_core_route_generator_basis_frontier_demo.context_product_generators.status",
    "finite_gates.idt_core_route_generator_basis_frontier_demo.recoverable_filter_generators.status",
    "finite_gates.idt_core_route_generator_basis_frontier_demo.state_effect_generators.status",
    "finite_gates.idt_core_route_grammar_audit_demo.bounded_correlation_arity_bound.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.bounded_correlation_generators.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.context_product_arity_bound.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.context_product_generators.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.finite_effect_registry.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.recoverable_filter_arity_bound.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.recoverable_filter_generators.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.route_closure_effect_audit.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.state_effect_generators.expected_component_status",
    "finite_gates.idt_core_route_grammar_audit_demo.state_effect_witness_arity_bound.expected_component_status",
    "finite_gates.idt_core_semantic_no_new_effects_audit_demo.joint_only_invariant_rejection.status",
    "finite_gates.idt_core_signature_registry_audit_demo.finite_claim_role_vocabulary.expected_component_status",
    "finite_gates.idt_core_signature_registry_audit_demo.finite_primitive_sort_vocabulary.expected_component_status",
    "finite_gates.idt_core_signature_registry_audit_demo.finite_route_family_registry.expected_component_status",
    "finite_gates.uniform_witness_bound_assumption_frontier_demo.bounded_context_arity.status",
    "finite_gates.uniform_witness_bound_assumption_frontier_demo.finite_context_signature.status",
    "finite_gates.uniform_witness_bound_assumption_frontier_demo.finite_route_generator_basis.status"
  ]

def currentFormalClaimCount : Nat := 33

structure RegistryWitness where
  id : String
  source : String
  items : List String
  expectedCount : Nat
  expectedDigest : String
  computedDigest : String
deriving Repr

def RegistryWitness.valid (w : RegistryWitness) : Bool :=
  w.items.length == w.expectedCount
    && w.expectedDigest == w.computedDigest
    && decide (w.items.Nodup)
    && decide (w.items.length > 0)

structure ArityWitness where
  id : String
  routeFamily : String
  arityBound : Nat
  uniformBound : Nat
  status : String
deriving Repr

def ArityWitness.valid (w : ArityWitness) : Bool :=
  w.status == "formal_proof"
    && decide (w.arityBound <= w.uniformBound)
    && decide (w.arityBound > 0)

structure GeneratorWitness where
  id : String
  routeFamily : String
  generatorRefs : List String
  status : String
deriving Repr

def GeneratorWitness.valid (w : GeneratorWitness) : Bool :=
  w.status == "formal_proof"
    && decide (w.generatorRefs.length > 0)
    && decide (w.generatorRefs.Nodup)

structure NoNewEffectWitness where
  id : String
  closedOverSources : List String
  newPrimitiveEffects : List String
  status : String
deriving Repr

def NoNewEffectWitness.valid (w : NoNewEffectWitness) : Bool :=
  w.status == "formal_proof"
    && w.newPrimitiveEffects == []
    && decide (w.closedOverSources.length > 0)

structure FormalAssumptionWitness where
  id : String
  status : String
  evidenceRefs : List String
  openGap : String
deriving Repr

def FormalAssumptionWitness.valid (w : FormalAssumptionWitness) : Bool :=
  w.status == "formal_proof"
    && w.openGap == ""
    && decide (w.evidenceRefs.length > 0)

structure PrimitiveCoreWitness where
  id : String
  primitiveStatus : String
  carrierStatus : String
  laws : List String
  expectedLaws : List String
  allowedDependencies : List String
  expectedAllowedDependencies : List String
  forbiddenRefHits : List String
deriving Repr

def PrimitiveCoreWitness.valid (w : PrimitiveCoreWitness) : Bool :=
  w.primitiveStatus == "idt_primitive"
    && w.carrierStatus == "carrier_neutral"
    && w.laws == w.expectedLaws
    && w.allowedDependencies == w.expectedAllowedDependencies
    && w.forbiddenRefHits == []
    && decide (w.laws.Nodup)
    && decide (w.laws.length > 0)

structure ImportObligationWitness where
  importId : String
  obligationKind : String
  target : String
  requiredStatus : String
  targetRefactor : String
  proofBoundary : String
deriving Repr

def ImportObligationWitness.valid (w : ImportObligationWitness) : Bool :=
  w.proofBoundary == "not_derived_from_idt_primitives"
    && w.requiredStatus != "formal_proof"
    && w.requiredStatus != "derived"
    && decide (w.target.length > 0)
    && decide (w.targetRefactor.length > 0)

structure FDCConditionWitness where
  id : String
  status : String
  expectedStatus : String
  evidenceRefs : List String
  openGap : String
  forbiddenRefHits : List String
deriving Repr

def FDCConditionWitness.valid (w : FDCConditionWitness) : Bool :=
  w.status == w.expectedStatus
    && w.expectedStatus == "candidate_principle"
    && w.forbiddenRefHits == []
    && decide (w.evidenceRefs.length > 0)
    && decide (w.openGap.length > 0)

structure FDCNegativeControlWitness where
  id : String
  expectedResult : String
  requiredResult : String
  evidenceRefs : List String
  retainedBoundary : String
deriving Repr

def FDCNegativeControlWitness.valid (w : FDCNegativeControlWitness) : Bool :=
  w.expectedResult == w.requiredResult
    && decide (w.evidenceRefs.length > 0)
    && decide (w.retainedBoundary.length > 0)

structure FDCOpenObligationWitness where
  id : String
  requiredStatus : String
  expectedRequiredStatus : String
deriving Repr

def FDCOpenObligationWitness.valid (w : FDCOpenObligationWitness) : Bool :=
  w.requiredStatus == w.expectedRequiredStatus
    && w.requiredStatus != "formal_proof"
    && w.requiredStatus != "derived"

structure QMWallNodeWitness where
  id : String
  result : String
  computedResult : String
  targetStatuses : List String
  importRefs : List String
  requiredImportRefs : List String
  openGap : String
deriving Repr

def QMWallNodeWitness.valid (w : QMWallNodeWitness) : Bool :=
  w.result == w.computedResult
    && w.result != "bad"
    && w.importRefs == w.requiredImportRefs
    && decide (w.targetStatuses.length > 0)
    && ((w.result == "pass" && w.openGap == "") || (w.result != "pass" && decide (w.openGap.length > 0)))

structure JointOnlyRejectionWitness where
  id : String
  status : String
  scope : String
  assumptions : List String
  separatorRefs : List String
  rejectedWitnessRefs : List String
  openGap : String
deriving Repr

def JointOnlyRejectionWitness.valid (w : JointOnlyRejectionWitness) : Bool :=
  w.status == "formal_proof"
    && w.scope == "finite_route_covered_context_product_composites"
    && w.openGap == ""
    && decide (w.assumptions.length > 0)
    && decide (w.separatorRefs.length > 0)
    && decide (w.rejectedWitnessRefs.length > 0)

def registryWitnesses : List RegistryWitness :=
[
  {
    id := "finite_claim_role_vocabulary",
    source := "theory_verifier.IDT_CORE_CLAIM_ROLE_REGISTRY",
    items := [
      "axiom",
      "blocked_claim",
      "bridge",
      "bridge_assumption",
      "calibration",
      "definition",
      "derived_readout",
      "dimensional_anchor",
      "dimensionless_coupling",
      "experimental_gate",
      "failure",
      "gate",
      "prediction",
      "primitive",
      "readout",
      "structural_selector",
      "theorem"
  ],
    expectedCount := 17,
    expectedDigest := "2a418a4b675ed8eb12a0a8b7d923ecd234e4dc5ee5168acf71f52cdc378296cf",
    computedDigest := "2a418a4b675ed8eb12a0a8b7d923ecd234e4dc5ee5168acf71f52cdc378296cf"
  },
  {
    id := "finite_gate_type_registry",
    source := "theory_verifier.FINITE_GATE_CHECKS",
    items := [
      "G_candidate_no_calibrated_input",
      "G_symbolic_clock_strain_candidate",
      "ab_flux_period",
      "ab_holonomy_phase",
      "action_anchor_lock_status",
      "action_frequency_threshold",
      "action_scale_gauge_obstruction",
      "action_standard_independence",
      "action_standard_provenance",
      "action_standard_work_time_provenance",
      "active_passive_inertial_equality",
      "actualization_i3_zero",
      "anisotropic_stress_norm",
      "barrier_transmission",
      "bell_chsh_from_amplitudes",
      "bell_chsh_table",
      "block_psd",
      "born_context_probability_table",
      "born_quadratic_readout_route",
      "bosonic_indistinguishability",
      "bounded_correlation_carrier_lemma_route",
      "bounded_correlation_screen_theorem",
      "bridge_assumption_boundary",
      "broader_generic_gpt_cone_frontier",
      "carrier_quantifier_frontier",
      "carrier_selection_frontier",
      "carrier_selection_proof_route",
      "clock_redshift",
      "clock_strain_variational_poisson",
      "clock_vacuum_pole_candidate",
      "clock_vacuum_pole_no_calibrated_input",
      "clock_vacuum_pole_universality",
      "clock_vacuum_stiffness_from_source_response",
      "clock_vacuum_stiffness_no_calibrated_input",
      "clock_vacuum_stiffness_universality",
      "coarse_grained_anisotropy",
      "combined_clock_rate",
      "composite_omega_bound",
      "conditional_inheritance_swap",
      "context_product_carrier_lemma_route",
      "context_product_exhaustion",
      "context_product_local_tomography_theorem",
      "context_transfer_no_cloning",
      "continuum_action_frontier",
      "contraction",
      "contraction_phase_degeneracy",
      "contraction_selection_no_calibrated_input",
      "cycle_cost_sum",
      "cycle_holonomy_class",
      "cycle_holonomy_composition",
      "cycle_holonomy_gauge_invariance",
      "delayed_context_partition",
      "diagonal_kernel_strain_cost",
      "dimensionful_anchor_policy",
      "dimensionless_coupling_policy",
      "distinguishability_geometry_probe",
      "domain_no_refit",
      "ell0_bound_not_value",
      "ell0_candidate_from_clock_pole",
      "ell0_candidate_no_gravity_input",
      "ell0_link_frequency_consistency",
      "ell0_no_gravity_input",
      "ell0_radar_consistency",
      "ell0_tick_bound",
      "facticizable_distinguishability_closure_frontier",
      "finite_weyl_relation",
      "fixed_point_component_status",
      "fixed_point_step_free_parameter_audit",
      "fixed_point_step_integer_obstruction",
      "fixed_point_step_no_gravity_input",
      "formal_proof_ledger_audit",
      "foundation_import_boundary_audit",
      "full_qm_closure_frontier",
      "fundamental_unknownness_bridge_audit",
      "generator_difference_convergence",
      "generic_gpt_classification_lemma_route",
      "generic_gpt_closure_separator",
      "generic_gpt_closure_theorem",
      "geometry_response_factor_freeze",
      "geometry_response_no_gravity_anchor",
      "gpt_principle_separator",
      "hbar_known_gate_holdout",
      "hilbert_spacetime_bridge_audit",
      "holonomy_selector_class_registry",
      "holonomy_selector_no_calibrated_input",
      "holonomy_selector_status",
      "holonomy_source_classification",
      "idt_bounded_correlation",
      "idt_core_finite_signature_frontier",
      "idt_core_gate_type_registry_audit",
      "idt_core_grammar_assumption_frontier",
      "idt_core_route_grammar_audit",
      "idt_core_semantic_no_new_effects_audit",
      "idt_core_signature_registry_audit",
      "idt_local_tomography_derivation",
      "idt_purification_filtering",
      "idt_structural_compression_audit",
      "kappa_omega_consistency",
      "kappa_omega_no_gravity_input",
      "ks_contextuality_obstruction",
      "local_tomography_separator",
      "marker_eraser_visibility",
      "matter_wave_bound",
      "measurement_facticity_route",
      "multipartite_contextuality",
      "newtonian_point_mass_clock_field",
      "no_cloning_context_invariance",
      "no_emergent_joint_only_invariant_route",
      "non_exact_holonomy_source",
      "noncomplex_jordan_classification_lemma_route",
      "noncomplex_jordan_separator",
      "noncomplex_jordan_separator_theorem",
      "nonfinite_gpt_residual_compactness",
      "nonfinite_gpt_residual_compactness_frontier",
      "nonfinite_gpt_residual_frontier",
      "one_parameter_unitary_flow",
      "partial_facticity_readout",
      "phase_action_scale_universality",
      "phase_branch_additivity",
      "phase_branch_no_postfit",
      "phase_cost_independence",
      "photon_dispersion_bound",
      "pointer_sector_stability",
      "ppn_gamma_from_potentials",
      "ppn_light_bending",
      "ppn_perihelion",
      "premeasurement_decoherence",
      "primitive_core_contract",
      "primitive_mass_anchor_inertia_response",
      "primitive_mass_anchor_no_quantum_gravity_input",
      "primitive_tick_clock_count",
      "primitive_tick_clock_universality",
      "primitive_tick_radar_consistency",
      "primitive_tick_reparam_invariance",
      "primitive_transition_phase_no_calibrated_input",
      "primitive_work_balance",
      "primitive_work_coarse_grain_balance",
      "primitive_work_dimensional_obstruction",
      "primitive_work_no_quantum_energy",
      "primitive_work_sector_universality",
      "probability_admissible_context",
      "projective_measurement_update",
      "psd_matrix",
      "purification_filtering_carrier_lemma_route",
      "purification_filtering_recoverable_support_theorem",
      "qm_core_recompile_route",
      "qm_proof_anti_hallucination_audit",
      "qm_wall_probe",
      "ramsey_clock_phase",
      "rebit_hidden_joint_invariant_separator",
      "recoverability_loss",
      "relative_phase_cost_family",
      "relative_phase_cost_from_edges",
      "relative_phase_cost_from_kernel_block_kernels",
      "relative_phase_cost_from_kernel_edges",
      "relative_phase_cost_from_kernel_holonomy",
      "relative_phase_cost_from_kernel_normalized_blocks",
      "relative_phase_cost_from_kernel_spectral_blocks",
      "relative_phase_cost_from_kernel_transfer_blocks",
      "relative_phase_cost_from_kernel_transfer_elements",
      "relative_phase_cost_from_kernel_unit_edges",
      "relative_phase_cost_from_kernel_unit_holonomy",
      "relative_phase_cost_from_spectral_kernel_blocks",
      "repeated_context_zeno",
      "research_graph_contract",
      "residual_acceleration_output",
      "residual_fit_claim_status",
      "residual_light_bending_output",
      "residual_no_postfit_provenance",
      "reversible_filter_closure_theorem",
      "rho_chi_no_gravity_input",
      "rho_chi_protocol_invariance",
      "route_closed_gpt_subtheory_frontier",
      "scale_residual_activation",
      "scale_residual_bound",
      "schur_psd",
      "screened_amplitude_lower_bound",
      "screened_baryonic_acceleration_map",
      "screened_baryonic_exponent_scan",
      "screened_baryonic_exponent_transfer",
      "screened_corridor_feasibility",
      "screened_observational_profile",
      "screened_profile_bound_status",
      "screened_profile_prediction",
      "screened_radius_scale_prediction",
      "screened_sparc_capacity",
      "screened_transition_bound",
      "sector_role_assignment_partition",
      "sector_role_registry",
      "sequential_sg_noncommuting_context",
      "shapiro_delay",
      "single_quantum_facticity",
      "slip_source_bound_from_anisotropy",
      "slip_source_poisson",
      "source_continuity",
      "source_flux_gauss",
      "source_law_coefficient",
      "source_response_charge_normalization",
      "source_response_no_calibrated_input",
      "source_response_packet_universality",
      "sparc_baryonic_residual_point",
      "sparc_residual_packet",
      "spectral_anchor_consistency",
      "spectral_kernel_diagonal_limit",
      "spectral_kernel_readout_covariance",
      "spectral_kernel_strain_cost",
      "spectral_law_free_parameter_audit",
      "spectral_law_no_calibrated_input",
      "spin_bell_angle_model",
      "stern_gerlach_context_readout",
      "stress_tensor_decomposition",
      "strong_continuity_modulus",
      "support_matching_phase_freedom",
      "temporal_facticity",
      "tensor_composition_route",
      "tick_scale_lock_status",
      "tomographic_state_effect_duality_theorem",
      "transition_phase_unit_readout",
      "translation_de_broglie_scale",
      "triple_path_sorkin_parameter",
      "two_level_update_oscillation",
      "two_path_interference_fringe",
      "uniform_witness_bound_assumption_frontier",
      "uniform_witness_bound_route",
      "unitary_generator_reconstruction",
      "unitary_graph_walk",
      "unitary_measurement_context",
      "unitary_network_probability",
      "winding_selector_additivity",
      "winding_selector_homotopy_consistency",
      "winding_selector_no_calibrated_input",
      "winding_selector_orientation_reversal",
      "work_scale_lock_status",
      "zero_stress_boundary_no_slip"
  ],
    expectedCount := 234,
    expectedDigest := "ad8a1dc48438b74ad28e0f62217330e4402513afac99ac590640cc47dff1e795",
    computedDigest := "ad8a1dc48438b74ad28e0f62217330e4402513afac99ac590640cc47dff1e795"
  },
  {
    id := "finite_primitive_sort_vocabulary",
    source := "theory_verifier.QM_EXPERIMENT_REQUIRED_PRIMITIVES",
    items := [
      "event",
      "distinguishability",
      "inheritance",
      "readout_context",
      "facticity",
      "stable_invariant"
  ],
    expectedCount := 6,
    expectedDigest := "c546f18003389499566b2c953c14744646cf6d79a1d3314765e2bea3b63e7dc5",
    computedDigest := "c546f18003389499566b2c953c14744646cf6d79a1d3314765e2bea3b63e7dc5"
  },
  {
    id := "finite_route_family_registry",
    source := "theory_verifier.IDT_CORE_ROUTE_FAMILY_REGISTRY",
    items := [
      "born_quadratic_readout_route_demo",
      "bounded_correlation_carrier_lemma_route_demo",
      "bounded_correlation_route",
      "carrier_selection_frontier_demo",
      "context_product_carrier_lemma_route_demo",
      "context_product_exhaustion_demo",
      "context_product_route",
      "generic_gpt_classification_lemma_route_demo",
      "generic_gpt_closure_separator_demo",
      "idt_bounded_correlation_demo",
      "idt_local_tomography_derivation_demo",
      "idt_purification_filtering_demo",
      "measurement_facticity_route_demo",
      "no_emergent_joint_only_invariant_route_demo",
      "noncomplex_jordan_classification_lemma_route_demo",
      "noncomplex_jordan_separator_demo",
      "purification_filtering_carrier_lemma_route_demo",
      "recoverable_filter_route",
      "state_effect_route",
      "tensor_composition_route_demo",
      "uniform_witness_bound_route_demo"
  ],
    expectedCount := 21,
    expectedDigest := "1db7ba1d6e45c4bb817f3cca9c9a8474a8b20fa0bce6b922a62aaf9d8728ea21",
    computedDigest := "1db7ba1d6e45c4bb817f3cca9c9a8474a8b20fa0bce6b922a62aaf9d8728ea21"
  }
]

def arityWitnesses : List ArityWitness :=
[
  {
    id := "context_product_arity_bound",
    routeFamily := "context_product_route",
    arityBound := 4,
    uniformBound := 4,
    status := "formal_proof"
  },
  {
    id := "state_effect_witness_arity_bound",
    routeFamily := "state_effect_route",
    arityBound := 4,
    uniformBound := 4,
    status := "formal_proof"
  },
  {
    id := "recoverable_filter_arity_bound",
    routeFamily := "recoverable_filter_route",
    arityBound := 3,
    uniformBound := 4,
    status := "formal_proof"
  },
  {
    id := "bounded_correlation_arity_bound",
    routeFamily := "bounded_correlation_route",
    arityBound := 4,
    uniformBound := 4,
    status := "formal_proof"
  }
]

def generatorWitnesses : List GeneratorWitness :=
[
  {
    id := "context_product_generators",
    routeFamily := "context_product_route",
    generatorRefs := [
      "context_product_exhaustion_demo",
      "context_product_exhaustion_implies_local_tomography"
  ],
    status := "formal_proof"
  },
  {
    id := "state_effect_generators",
    routeFamily := "state_effect_route",
    generatorRefs := [
      "tomographic_state_effect_duality_theorem_demo",
      "route_witness_completeness_implies_tomographic_state_effect_duality"
  ],
    status := "formal_proof"
  },
  {
    id := "recoverable_filter_generators",
    routeFamily := "recoverable_filter_route",
    generatorRefs := [
      "reversible_filter_closure_theorem_demo",
      "recoverable_support_update_implies_reversible_filter_closure"
  ],
    status := "formal_proof"
  },
  {
    id := "bounded_correlation_generators",
    routeFamily := "bounded_correlation_route",
    generatorRefs := [
      "bounded_correlation_screen_theorem_demo",
      "bounded_correlation_screen_rejects_superquantum_boxes"
  ],
    status := "formal_proof"
  }
]

def noNewEffectWitnesses : List NoNewEffectWitness :=
[
  {
    id := "finite_effect_registry",
    closedOverSources := [
      "idt_core_finite_signature_frontier_demo",
      "theory_verifier.QM_EXPERIMENT_REQUIRED_PRIMITIVES",
      "theory_verifier.IDT_CORE_ROUTE_FAMILY_REGISTRY"
  ],
    newPrimitiveEffects := [],
    status := "formal_proof"
  },
  {
    id := "route_closure_effect_audit",
    closedOverSources := [
      "uniform_witness_bound_route_demo",
      "idt_core_route_grammar_audit_demo",
      "nonfinite_gpt_residual_frontier_demo"
  ],
    newPrimitiveEffects := [],
    status := "formal_proof"
  }
]

def formalAssumptionWitnesses : List FormalAssumptionWitness :=
[
  {
    id := "finite_context_signature",
    status := "formal_proof",
    evidenceRefs := [
      "idt_core_finite_signature_frontier_demo",
      "idt_core_signature_registry_audit_demo",
      "idt_core_gate_type_registry_audit_demo"
  ],
    openGap := ""
  },
  {
    id := "bounded_context_arity",
    status := "formal_proof",
    evidenceRefs := [
      "idt_core_bounded_arity_frontier_demo",
      "idt_core_route_grammar_audit_demo"
  ],
    openGap := ""
  },
  {
    id := "finite_route_generator_basis",
    status := "formal_proof",
    evidenceRefs := [
      "idt_core_route_generator_basis_frontier_demo",
      "idt_core_route_grammar_audit_demo"
  ],
    openGap := ""
  }
]

def primitiveCoreWitnesses : List PrimitiveCoreWitness :=
[
  {
    id := "history_space",
    primitiveStatus := "idt_primitive",
    carrierStatus := "carrier_neutral",
    laws := [
      "carrier_neutral_history_domain",
      "event_bundle_identity"
  ],
    expectedLaws := [
      "carrier_neutral_history_domain",
      "event_bundle_identity"
  ],
    allowedDependencies := [
      "sections/01-primitives.md"
  ],
    expectedAllowedDependencies := [
      "sections/01-primitives.md"
  ],
    forbiddenRefHits := []
  },
  {
    id := "event_algebra",
    primitiveStatus := "idt_primitive",
    carrierStatus := "carrier_neutral",
    laws := [
      "contains_empty_and_total_events",
      "closed_under_finite_union",
      "closed_under_complement"
  ],
    expectedLaws := [
      "contains_empty_and_total_events",
      "closed_under_finite_union",
      "closed_under_complement"
  ],
    allowedDependencies := [
      "sections/01-primitives.md"
  ],
    expectedAllowedDependencies := [
      "sections/01-primitives.md"
  ],
    forbiddenRefHits := []
  },
  {
    id := "readout_context_family",
    primitiveStatus := "idt_primitive",
    carrierStatus := "carrier_neutral",
    laws := [
      "contexts_are_event_partitions",
      "readouts_are_carrier_neutral"
  ],
    expectedLaws := [
      "contexts_are_event_partitions",
      "readouts_are_carrier_neutral"
  ],
    allowedDependencies := [
      "sections/01-primitives.md"
  ],
    expectedAllowedDependencies := [
      "sections/01-primitives.md"
  ],
    forbiddenRefHits := []
  },
  {
    id := "inheritance_act_family",
    primitiveStatus := "idt_primitive",
    carrierStatus := "carrier_neutral",
    laws := [
      "acts_map_contexts_to_contexts",
      "acts_preserve_carrier_neutrality"
  ],
    expectedLaws := [
      "acts_map_contexts_to_contexts",
      "acts_preserve_carrier_neutrality"
  ],
    allowedDependencies := [
      "sections/01-primitives.md"
  ],
    expectedAllowedDependencies := [
      "sections/01-primitives.md"
  ],
    forbiddenRefHits := []
  }
]

def importObligationWitnesses : List ImportObligationWitness :=
[
  {
    importId := "complex_amplitude_carrier",
    obligationKind := "theorem_card",
    target := "universal_carrier_selection_theorem",
    requiredStatus := "open",
    targetRefactor := "carrier_neutral_K_I",
    proofBoundary := "not_derived_from_idt_primitives"
  },
  {
    importId := "psd_distinguishability_kernel",
    obligationKind := "qm_core_obligation",
    target := "distinguishability_geometry",
    requiredStatus := "target",
    targetRefactor := "positivity_obligation",
    proofBoundary := "not_derived_from_idt_primitives"
  },
  {
    importId := "quadratic_actualization_measure",
    obligationKind := "theorem_card",
    target := "universal_born_rule_theorem",
    requiredStatus := "open",
    targetRefactor := "born_rule_obligation",
    proofBoundary := "not_derived_from_idt_primitives"
  },
  {
    importId := "schur_inheritance_update",
    obligationKind := "qm_core_obligation",
    target := "measurement_facticity_mechanism",
    requiredStatus := "regression_supported",
    targetRefactor := "inheritance_update_obligation",
    proofBoundary := "not_derived_from_idt_primitives"
  },
  {
    importId := "tensor_composition_import",
    obligationKind := "theorem_card",
    target := "monoidal_tensor_composition_theorem",
    requiredStatus := "open",
    targetRefactor := "monoidal_composition_obligation",
    proofBoundary := "not_derived_from_idt_primitives"
  },
  {
    importId := "unitary_context_map_import",
    obligationKind := "theorem_card",
    target := "wigner_reversible_inheritance_theorem",
    requiredStatus := "open",
    targetRefactor := "reversible_inheritance_obligation",
    proofBoundary := "not_derived_from_idt_primitives"
  },
  {
    importId := "action_phase_hbar_bridge",
    obligationKind := "qm_core_obligation",
    target := "continuum_action_scale_extension",
    requiredStatus := "blocked",
    targetRefactor := "first_principles_action_scale_obligation",
    proofBoundary := "not_derived_from_idt_primitives"
  }
]

def fdcTargetPrinciple : String := "facticizable_distinguishability_closure"

def fdcClosureRule : String := "stable_inherited_distinguishability_requires_finite_readout_witness"

def fdcForbiddenUpgrades : List String :=
  [
    "does_not_prove_full_QM_I",
    "does_not_prove_Born_rule",
    "does_not_select_Hilbert_carrier",
    "does_not_close_nonfinite_gpt_residual",
    "does_not_import_QM_structures_as_primitives"
  ]

def fdcConditionWitnesses : List FDCConditionWitness :=
[
  {
    id := "stable_inherited_distinguishability",
    status := "candidate_principle",
    expectedStatus := "candidate_principle",
    evidenceRefs := [
      "distinguishability_geometry_probe_demo"
  ],
    openGap := "Candidate IDT closure principle; this is not yet a universal derivation of QM.",
    forbiddenRefHits := []
  },
  {
    id := "admissible_readout_facticization",
    status := "candidate_principle",
    expectedStatus := "candidate_principle",
    evidenceRefs := [
      "measurement_facticity_route_demo"
  ],
    openGap := "Candidate IDT closure principle; this is not yet a universal derivation of QM.",
    forbiddenRefHits := []
  },
  {
    id := "finite_route_witness_coverage",
    status := "candidate_principle",
    expectedStatus := "candidate_principle",
    evidenceRefs := [
      "context_product_exhaustion_demo",
      "idt_core_route_grammar_audit_demo"
  ],
    openGap := "Candidate IDT closure principle; this is not yet a universal derivation of QM.",
    forbiddenRefHits := []
  },
  {
    id := "no_unfacticizable_stable_invariant",
    status := "candidate_principle",
    expectedStatus := "candidate_principle",
    evidenceRefs := [
      "idt_core_semantic_no_new_effects_audit_demo",
      "no_emergent_joint_only_invariant_route_demo"
  ],
    openGap := "Candidate IDT closure principle; this is not yet a universal derivation of QM.",
    forbiddenRefHits := []
  }
]

def fdcNegativeControlWitnesses : List FDCNegativeControlWitness :=
[
  {
    id := "hidden_joint_only_invariant",
    expectedResult := "rejected_under_fdc",
    requiredResult := "rejected_under_fdc",
    evidenceRefs := [
      "real_hilbert_composite_hidden_joint_invariant_demo",
      "context_product_exhaustion_implies_local_tomography"
  ],
    retainedBoundary := "Negative control only; this does not close full QM or import QM structure as primitive."
  },
  {
    id := "global_noncontextual_fact_table",
    expectedResult := "rejected_under_fdc",
    requiredResult := "rejected_under_fdc",
    evidenceRefs := [
      "ks_contextuality_obstruction_demo",
      "multipartite_contextuality_demo"
  ],
    retainedBoundary := "Negative control only; this does not close full QM or import QM structure as primitive."
  },
  {
    id := "unconstrained_generic_gpt_cone",
    expectedResult := "rejected_under_fdc",
    requiredResult := "rejected_under_fdc",
    evidenceRefs := [
      "generic_gpt_closure_separator_demo"
  ],
    retainedBoundary := "Negative control only; this does not close full QM or import QM structure as primitive."
  },
  {
    id := "nonfinite_unwitnessed_residual",
    expectedResult := "remains_open",
    requiredResult := "remains_open",
    evidenceRefs := [
      "nonfinite_gpt_residual_frontier_demo"
  ],
    retainedBoundary := "Negative control only; this does not close full QM or import QM structure as primitive."
  }
]

def fdcOpenObligationWitnesses : List FDCOpenObligationWitness :=
[
  {
    id := "universal_carrier_selection_theorem",
    requiredStatus := "open",
    expectedRequiredStatus := "open"
  },
  {
    id := "hilbert_carrier_derivation",
    requiredStatus := "blocked",
    expectedRequiredStatus := "blocked"
  },
  {
    id := "universal_born_rule_theorem",
    requiredStatus := "open",
    expectedRequiredStatus := "open"
  },
  {
    id := "wigner_reversible_inheritance_theorem",
    requiredStatus := "open",
    expectedRequiredStatus := "open"
  },
  {
    id := "monoidal_tensor_composition_theorem",
    requiredStatus := "open",
    expectedRequiredStatus := "open"
  }
]

def qmWallProbeTarget : String := "full_QM_I"

def qmWallProbeForbiddenUpgrades : List String :=
  [
    "does_not_prove_full_QM_I",
    "does_not_prove_absence_of_future_wall",
    "does_not_treat_open_as_pass",
    "does_not_hide_QM_imports",
    "does_not_upgrade_blocked_to_open_without_proof",
    "does_not_reclassify_candidate_principles_as_formal_proof"
  ]

def qmWallNodeWitnesses : List QMWallNodeWitness :=
[
  {
    id := "primitive_core_boundary",
    result := "pass",
    computedResult := "pass",
    targetStatuses := [
      "primitive_core_locked"
  ],
    importRefs := [],
    requiredImportRefs := [],
    openGap := ""
  },
  {
    id := "fdc_lower_principle",
    result := "open",
    computedResult := "open",
    targetStatuses := [
      "frontier_candidate"
  ],
    importRefs := [],
    requiredImportRefs := [],
    openGap := "FDC is a candidate principle, not a completed full-QM derivation."
  },
  {
    id := "context_product_local_tomography",
    result := "pass",
    computedResult := "pass",
    targetStatuses := [
      "conditional_proof"
  ],
    importRefs := [],
    requiredImportRefs := [],
    openGap := ""
  },
  {
    id := "distinguishability_geometry",
    result := "open",
    computedResult := "open",
    targetStatuses := [
      "target"
  ],
    importRefs := [
      "psd_distinguishability_kernel"
  ],
    requiredImportRefs := [
      "psd_distinguishability_kernel"
  ],
    openGap := "The PSD geometry is still an explicit obligation, not a primitive-core theorem."
  },
  {
    id := "probability_measure_layer",
    result := "pass",
    computedResult := "pass",
    targetStatuses := [
      "regression_supported"
  ],
    importRefs := [],
    requiredImportRefs := [],
    openGap := ""
  },
  {
    id := "measurement_facticity_mechanism",
    result := "open",
    computedResult := "open",
    targetStatuses := [
      "regression_supported"
  ],
    importRefs := [
      "schur_inheritance_update"
  ],
    requiredImportRefs := [
      "schur_inheritance_update"
  ],
    openGap := "Measurement facticity is regression-supported but still carries the Schur update import."
  },
  {
    id := "carrier_selection",
    result := "open",
    computedResult := "open",
    targetStatuses := [
      "open"
  ],
    importRefs := [
      "complex_amplitude_carrier"
  ],
    requiredImportRefs := [
      "complex_amplitude_carrier"
  ],
    openGap := "Carrier selection remains open; current finite separators are not a universal theorem."
  },
  {
    id := "hilbert_carrier_derivation",
    result := "wall",
    computedResult := "wall",
    targetStatuses := [
      "blocked",
      "blocked"
  ],
    importRefs := [
      "complex_amplitude_carrier"
  ],
    requiredImportRefs := [
      "complex_amplitude_carrier"
  ],
    openGap := "Hilbert carrier derivation is currently blocked by the carrier import boundary."
  },
  {
    id := "born_rule_derivation",
    result := "wall",
    computedResult := "wall",
    targetStatuses := [
      "open",
      "blocked"
  ],
    importRefs := [
      "quadratic_actualization_measure"
  ],
    requiredImportRefs := [
      "quadratic_actualization_measure"
  ],
    openGap := "The universal Born derivation is blocked at the quadratic actualization obligation."
  },
  {
    id := "tensor_composition",
    result := "open",
    computedResult := "open",
    targetStatuses := [
      "open",
      "target"
  ],
    importRefs := [
      "tensor_composition_import"
  ],
    requiredImportRefs := [
      "tensor_composition_import"
  ],
    openGap := "Tensor composition is still a target/open obligation."
  },
  {
    id := "reversible_dynamics",
    result := "open",
    computedResult := "open",
    targetStatuses := [
      "open"
  ],
    importRefs := [
      "unitary_context_map_import"
  ],
    requiredImportRefs := [
      "unitary_context_map_import"
  ],
    openGap := "Wigner-style reversible inheritance remains open."
  },
  {
    id := "experiment_recompile_from_core",
    result := "open",
    computedResult := "open",
    targetStatuses := [
      "target"
  ],
    importRefs := [
      "complex_amplitude_carrier",
      "quadratic_actualization_measure",
      "tensor_composition_import",
      "unitary_context_map_import"
  ],
    requiredImportRefs := [
      "complex_amplitude_carrier",
      "quadratic_actualization_measure",
      "tensor_composition_import",
      "unitary_context_map_import"
  ],
    openGap := "The 35-experiment corpus is covered by gates, but not yet recompiled from the primitive core."
  },
  {
    id := "continuum_action_scale",
    result := "wall",
    computedResult := "wall",
    targetStatuses := [
      "blocked",
      "blocked"
  ],
    importRefs := [
      "action_phase_hbar_bridge"
  ],
    requiredImportRefs := [
      "action_phase_hbar_bridge"
  ],
    openGap := "The action scale remains blocked as a first-principles derivation."
  }
]

def jointOnlyRejectionWitness : JointOnlyRejectionWitness :=
{
  id := "joint_only_invariant_rejection",
  status := "formal_proof",
  scope := "finite_route_covered_context_product_composites",
  assumptions := [
    "context_product_exhaustion",
    "product_effect_separation",
    "stable_invariant_witness_completeness",
    "facticized_readout_closure"
  ],
  separatorRefs := [
    "context_product_exhaustion_implies_local_tomography",
    "context_product_local_tomography_theorem_demo",
    "context_product_exhaustion_demo"
  ],
  rejectedWitnessRefs := [
    "real_hilbert_composite_hidden_joint_invariant",
    "real_hilbert_composite_hidden_joint_invariant_demo"
  ],
  openGap := ""
}

def currentSemanticProofChecks : List Bool :=
  [
    registryWitnesses.all RegistryWitness.valid,
    arityWitnesses.all ArityWitness.valid,
    generatorWitnesses.all GeneratorWitness.valid,
    noNewEffectWitnesses.all NoNewEffectWitness.valid,
    formalAssumptionWitnesses.all FormalAssumptionWitness.valid,
    primitiveCoreWitnesses.all PrimitiveCoreWitness.valid,
    importObligationWitnesses.all ImportObligationWitness.valid,
    fdcTargetPrinciple == "facticizable_distinguishability_closure",
    fdcClosureRule == "stable_inherited_distinguishability_requires_finite_readout_witness",
    fdcForbiddenUpgrades.length == 5,
    fdcConditionWitnesses.all FDCConditionWitness.valid,
    fdcNegativeControlWitnesses.all FDCNegativeControlWitness.valid,
    fdcOpenObligationWitnesses.all FDCOpenObligationWitness.valid,
    qmWallProbeTarget == "full_QM_I",
    qmWallProbeForbiddenUpgrades.length == 6,
    qmWallNodeWitnesses.all QMWallNodeWitness.valid,
    jointOnlyRejectionWitness.valid
  ]

theorem current_formal_claim_ledger_count :
    currentFormalClaimRefs.length = currentFormalClaimCount := by
  native_decide

theorem current_formal_claim_ledger_nonempty :
    currentFormalClaimRefs.length > 0 := by
  native_decide

theorem current_formal_claim_ledger_nodup :
    currentFormalClaimRefs.Nodup := by
  native_decide

theorem current_signature_registry_witnesses_valid :
    registryWitnesses.all RegistryWitness.valid = true := by
  native_decide

theorem current_bounded_arity_witnesses_valid :
    arityWitnesses.all ArityWitness.valid = true := by
  native_decide

theorem current_route_generator_witnesses_valid :
    generatorWitnesses.all GeneratorWitness.valid = true := by
  native_decide

theorem current_no_new_effect_witnesses_valid :
    noNewEffectWitnesses.all NoNewEffectWitness.valid = true := by
  native_decide

theorem current_formal_assumption_witnesses_valid :
    formalAssumptionWitnesses.all FormalAssumptionWitness.valid = true := by
  native_decide

theorem current_primitive_core_witnesses_valid :
    primitiveCoreWitnesses.all PrimitiveCoreWitness.valid = true := by
  native_decide

theorem current_import_obligation_witnesses_valid :
    importObligationWitnesses.all ImportObligationWitness.valid = true := by
  native_decide

theorem current_fdc_condition_witnesses_valid :
    fdcConditionWitnesses.all FDCConditionWitness.valid = true := by
  native_decide

theorem current_fdc_negative_control_witnesses_valid :
    fdcNegativeControlWitnesses.all FDCNegativeControlWitness.valid = true := by
  native_decide

theorem current_fdc_open_obligation_witnesses_valid :
    fdcOpenObligationWitnesses.all FDCOpenObligationWitness.valid = true := by
  native_decide

theorem current_qm_wall_node_witnesses_valid :
    qmWallNodeWitnesses.all QMWallNodeWitness.valid = true := by
  native_decide

theorem current_joint_only_rejection_witness_valid :
    jointOnlyRejectionWitness.valid = true := by
  native_decide

theorem current_semantic_proof_checks_pass :
    currentSemanticProofChecks.all (fun check => check) = true := by
  native_decide

end IDT
