from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from typing import Literal

Verdict = Literal["J_DERIVATION_HIT", "IMPORTED_HIT", "NEAR_MISS", "REJECTED"]
TestVerdict = Literal["PASS", "FAIL"]
Vector = tuple[float, float]
Matrix = tuple[tuple[float, float], tuple[float, float]]


@dataclass(frozen=True)
class TransportCandidate:
    name: str
    mode: Literal["rotation", "identity", "hyperbolic", "shear"]
    omega: float
    imports: tuple[str, ...]
    description: str


@dataclass(frozen=True)
class TestResult:
    name: str
    verdict: TestVerdict
    reason: str
    details: dict[str, float | int | str | bool]


@dataclass(frozen=True)
class CandidateResult:
    candidate: str
    verdict: Verdict
    passed: int
    failed: int
    imports: tuple[str, ...]
    tests: list[TestResult]
    description: str


CANDIDATES: tuple[TransportCandidate, ...] = (
    TransportCandidate("no_phase_identity", "identity", 0.0, (), "no quadrature partner"),
    TransportCandidate("half_speed_rotation", "rotation", 0.5, (), "norm-preserving transport with wrong phase scale"),
    TransportCandidate("double_speed_rotation", "rotation", 2.0, (), "norm-preserving transport with doubled phase scale"),
    TransportCandidate("canonical_quadrature_J", "rotation", 1.0, (), "quadrature transport generated by J^2=-I"),
    TransportCandidate("imported_complex_J", "rotation", 1.0, ("complex_scalar_assumed",), "control that imports complex phase"),
    TransportCandidate("hyperbolic_transport", "hyperbolic", 1.0, (), "reversible but non-norm-preserving split generator"),
    TransportCandidate("shear_transport", "shear", 1.0, (), "reversible shear context transport"),
)


def matmul(left: Matrix, right: Matrix) -> Matrix:
    return (
        (
            left[0][0] * right[0][0] + left[0][1] * right[1][0],
            left[0][0] * right[0][1] + left[0][1] * right[1][1],
        ),
        (
            left[1][0] * right[0][0] + left[1][1] * right[1][0],
            left[1][0] * right[0][1] + left[1][1] * right[1][1],
        ),
    )


def matvec(matrix: Matrix, vector: Vector) -> Vector:
    return (
        matrix[0][0] * vector[0] + matrix[0][1] * vector[1],
        matrix[1][0] * vector[0] + matrix[1][1] * vector[1],
    )


def dot(left: Vector, right: Vector) -> float:
    return left[0] * right[0] + left[1] * right[1]


def norm(vector: Vector) -> float:
    return math.sqrt(dot(vector, vector))


def transport(candidate: TransportCandidate, theta: float) -> Matrix:
    if candidate.mode == "identity":
        return ((1.0, 0.0), (0.0, 1.0))
    if candidate.mode == "rotation":
        angle = candidate.omega * theta
        c = math.cos(angle)
        s = math.sin(angle)
        return ((c, -s), (s, c))
    if candidate.mode == "hyperbolic":
        value = candidate.omega * theta
        c = math.cosh(value)
        s = math.sinh(value)
        return ((c, s), (s, c))
    if candidate.mode == "shear":
        return ((1.0, candidate.omega * theta), (0.0, 1.0))
    raise ValueError(f"unknown mode: {candidate.mode}")


def matrix_error(left: Matrix, right: Matrix) -> float:
    return max(abs(left[row][column] - right[row][column]) for row in range(2) for column in range(2))


def transport_group_test(candidate: TransportCandidate) -> TestResult:
    max_error = 0.0
    identity = transport(candidate, 0.0)
    max_error = max(max_error, matrix_error(identity, ((1.0, 0.0), (0.0, 1.0))))
    for a in (-1.0, -0.25, 0.0, 0.5, 1.25):
        inverse_product = matmul(transport(candidate, a), transport(candidate, -a))
        max_error = max(max_error, matrix_error(inverse_product, ((1.0, 0.0), (0.0, 1.0))))
        for b in (-0.75, 0.25, 1.5):
            composed = matmul(transport(candidate, a), transport(candidate, b))
            direct = transport(candidate, a + b)
            max_error = max(max_error, matrix_error(composed, direct))
    if max_error <= 1e-12:
        return TestResult("transport_group", "PASS", "context transport is a reversible one-parameter group", {"max_error": round(max_error, 15)})
    return TestResult("transport_group", "FAIL", "context transport does not form a reversible one-parameter group", {"max_error": round(max_error, 12)})


def norm_preservation_test(candidate: TransportCandidate) -> TestResult:
    vectors: tuple[Vector, ...] = ((1.0, 0.0), (0.0, 1.0), (1.0, 2.0), (-0.5, 1.25))
    max_error = 0.0
    for vector in vectors:
        base = norm(vector)
        for theta in (-math.pi, -0.5, 0.25, math.pi / 2.0, math.pi):
            moved = matvec(transport(candidate, theta), vector)
            max_error = max(max_error, abs(norm(moved) - base))
    if max_error <= 1e-12:
        return TestResult("norm_preservation", "PASS", "transport preserves support norm", {"max_error": round(max_error, 15)})
    return TestResult("norm_preservation", "FAIL", "transport changes support norm", {"max_error": round(max_error, 12)})


def quadrature_scale_test(candidate: TransportCandidate) -> TestResult:
    base = (1.0, 0.0)
    quarter = matvec(transport(candidate, math.pi / 2.0), base)
    half = matvec(transport(candidate, math.pi), base)
    quarter_dot = dot(base, quarter)
    quarter_norm_error = abs(norm(quarter) - 1.0)
    half_error = math.hypot(half[0] + 1.0, half[1])
    if abs(quarter_dot) <= 1e-12 and quarter_norm_error <= 1e-12 and half_error <= 1e-12:
        return TestResult(
            "quadrature_scale",
            "PASS",
            "quarter-turn creates an orthogonal equal-norm partner and half-turn gives opposite orientation",
            {"quarter_dot": round(quarter_dot, 15), "quarter_norm_error": round(quarter_norm_error, 15), "half_error": round(half_error, 15)},
        )
    return TestResult(
        "quadrature_scale",
        "FAIL",
        "transport does not fix the required quadrature/phase scale",
        {"quarter_dot": round(quarter_dot, 12), "quarter_norm_error": round(quarter_norm_error, 12), "half_error": round(half_error, 12)},
    )


def phase_gauge_test(candidate: TransportCandidate) -> TestResult:
    base = (1.0, 0.0)
    max_error = 0.0
    for theta in (0.0, 0.25, math.pi / 3.0, math.pi / 2.0, math.pi):
        moved = matvec(transport(candidate, theta), base)
        probability = (dot(base, moved) ** 2 + dot((0.0, 1.0), moved) ** 2) / (norm(base) * norm(moved)) ** 2
        max_error = max(max_error, abs(probability - 1.0))
    if max_error <= 1e-12:
        return TestResult("phase_gauge", "PASS", "global quadrature transport remains a gauge orbit of the same support", {"max_error": round(max_error, 15)})
    return TestResult("phase_gauge", "FAIL", "global quadrature transport is exposed as a distinct support state", {"max_error": round(max_error, 12)})


def relative_phase_interference_test(candidate: TransportCandidate) -> TestResult:
    base = (1.0, 0.0)
    max_error = 0.0
    for index in range(65):
        theta = 2.0 * math.pi * index / 64.0
        moved = matvec(transport(candidate, theta), base)
        amplitude = (1.0 + dot(base, moved)) / 2.0
        expected = math.cos(theta / 2.0) ** 2
        max_error = max(max_error, abs(amplitude - expected))
    if max_error <= 1e-12:
        return TestResult("relative_phase_interference", "PASS", "relative phase exposes the cosine-squared interference law", {"max_error": round(max_error, 15)})
    return TestResult("relative_phase_interference", "FAIL", "relative phase interference law is not recovered", {"max_error": round(max_error, 12)})


def import_screen(candidate: TransportCandidate) -> TestResult:
    if candidate.imports:
        return TestResult("import_screen", "FAIL", "candidate imports phase/complex structure", {"imports": ",".join(candidate.imports)})
    return TestResult("import_screen", "PASS", "no phase/complex import declared", {"imports": "-"})


def evaluate_candidate(candidate: TransportCandidate) -> CandidateResult:
    tests = [
        transport_group_test(candidate),
        norm_preservation_test(candidate),
        quadrature_scale_test(candidate),
        phase_gauge_test(candidate),
        relative_phase_interference_test(candidate),
        import_screen(candidate),
    ]
    passed = sum(1 for test in tests if test.verdict == "PASS")
    failed = len(tests) - passed
    if passed == len(tests):
        verdict: Verdict = "J_DERIVATION_HIT"
    elif candidate.imports and passed >= len(tests) - 1:
        verdict = "IMPORTED_HIT"
    elif passed >= 4:
        verdict = "NEAR_MISS"
    else:
        verdict = "REJECTED"
    return CandidateResult(
        candidate=candidate.name,
        verdict=verdict,
        passed=passed,
        failed=failed,
        imports=candidate.imports,
        tests=tests,
        description=candidate.description,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Derive or kill the phase-bundle J/quadrature structure in one pass.")
    parser.add_argument("--output-jsonl", default="")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    order = {"J_DERIVATION_HIT": 4, "IMPORTED_HIT": 3, "NEAR_MISS": 2, "REJECTED": 1}
    results = sorted((evaluate_candidate(candidate) for candidate in CANDIDATES), key=lambda result: (order[result.verdict], result.passed), reverse=True)
    for result in results:
        imports = ",".join(result.imports) if result.imports else "-"
        print(f"verdict={result.verdict} candidate={result.candidate} passed={result.passed}/6 imports={imports}")
        for test in result.tests:
            print(f"  {test.verdict} {test.name}: {test.reason} details={test.details}")
    if args.output_jsonl:
        with open(str(args.output_jsonl), "w", encoding="utf-8") as handle:
            for result in results:
                handle.write(json.dumps(asdict(result), sort_keys=True) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
