from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path
from typing import TextIO


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from theory_verifier.core import iter_formal_claims, load_manifest  # noqa: E402

DEFAULT_MANIFEST = ROOT / "theory_verifier_manifest_v6_0.json"
DEFAULT_LEAN_PATH = ROOT / "Proofs" / "IDTCore.lean"


def lean_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def formal_claim_refs(manifest_path: Path) -> tuple[str, ...]:
    manifest = load_manifest(manifest_path)
    return tuple(sorted({claim.reference for claim in iter_formal_claims(manifest)}))


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def render_lean(claim_refs: Sequence[str]) -> str:
    entries: list[str] = []
    for index, claim_ref in enumerate(claim_refs):
        suffix = "," if index < len(claim_refs) - 1 else ""
        entries.append(f"    {lean_string(claim_ref)}{suffix}")
    rendered_entries = "\n".join(entries)
    if claim_refs:
        cardinality_theorem = """theorem current_formal_claim_ledger_nonempty :
    currentFormalClaimRefs.length > 0 := by
  native_decide"""
    else:
        cardinality_theorem = """theorem current_formal_claim_ledger_empty :
    currentFormalClaimRefs = [] := by
  native_decide"""
    return f"""-- Generated by scripts/sync_formal_proof_ledger.py. Do not edit by hand.

namespace IDT

def currentFormalClaimRefs : List String :=
  [
{rendered_entries}
  ]

def currentFormalClaimCount : Nat := {len(claim_refs)}

theorem current_formal_claim_ledger_count :
    currentFormalClaimRefs.length = currentFormalClaimCount := by
  native_decide

{cardinality_theorem}

theorem current_formal_claim_ledger_nodup :
    currentFormalClaimRefs.Nodup := by
  native_decide

end IDT
"""


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as temp_file:
        temp_path = Path(temp_file.name)
        temp_file.write(content)
        temp_file.flush()
        os.fsync(temp_file.fileno())
    os.replace(temp_path, path)


def check_ledger(manifest_path: Path, lean_path: Path, output: TextIO) -> int:
    claim_refs = formal_claim_refs(manifest_path)
    expected = render_lean(claim_refs)
    try:
        actual = lean_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        output.write(
            json.dumps(
                {
                    "ok": False,
                    "reason": "lean_ledger_missing",
                    "path": display_path(lean_path),
                    "claim_count": len(claim_refs),
                },
                indent=2,
            )
        )
        output.write("\n")
        return 1
    if actual != expected:
        output.write(
            json.dumps(
                {
                    "ok": False,
                    "reason": "lean_ledger_out_of_sync",
                    "path": display_path(lean_path),
                    "claim_count": len(claim_refs),
                },
                indent=2,
            )
        )
        output.write("\n")
        return 1
    output.write(
        json.dumps(
            {
                "ok": True,
                "path": display_path(lean_path),
                "claim_count": len(claim_refs),
            },
            indent=2,
        )
    )
    output.write("\n")
    return 0


def write_ledger(manifest_path: Path, lean_path: Path, output: TextIO) -> int:
    claim_refs = formal_claim_refs(manifest_path)
    content = render_lean(claim_refs)
    if lean_path.exists() and lean_path.read_text(encoding="utf-8") == content:
        changed = False
    else:
        write_atomic(lean_path, content)
        changed = True
    output.write(
        json.dumps(
            {
                "ok": True,
                "path": display_path(lean_path),
                "claim_count": len(claim_refs),
                "changed": changed,
            },
            indent=2,
        )
    )
    output.write("\n")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Synchronize the generated Lean ledger of formal proof claims.")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--lean-path", type=Path, default=DEFAULT_LEAN_PATH)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Fail if the Lean ledger is out of sync.")
    mode.add_argument("--write", action="store_true", help="Rewrite the generated Lean ledger.")
    return parser


def main(argv: Sequence[str] | None = None, output: TextIO | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    stream = output if output is not None else sys.stdout
    manifest_path = args.manifest if args.manifest.is_absolute() else ROOT / args.manifest
    lean_path = args.lean_path if args.lean_path.is_absolute() else ROOT / args.lean_path
    if args.write:
        return write_ledger(manifest_path, lean_path, stream)
    return check_ledger(manifest_path, lean_path, stream)


if __name__ == "__main__":
    raise SystemExit(main())
